import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import RootLayout from "@/components/layout/rootLayout/RootLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Touch",
  description: "Generated by create next app",
};

export default function MainRootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
 
 
  return (
    <html lang="en">
      <body className={inter.className}>
        <RootLayout >
          {children}
        </RootLayout>
      </body>
    </html>
  );
}
